### ISSUE TITLE
Update restic backends

### ISSUE THREAD

**Issue by rawtaz** [Roman2K/scat#19]
Hi!

I noticed that restic is listed in the README, and that's interesting, but the list of backends for it is not accurate. Restic currently supports the following backends:
- [Local directory](https://restic.readthedocs.io/en/latest/manual.html#local)
- [sftp server (via SSH)](https://restic.readthedocs.io/en/latest/manual.html#sftp)
- [HTTP REST server](https://restic.readthedocs.io/en/latest/manual.html#rest-server) ([protocol](doc/rest_backend.rst) [rest-server](https://github.com/restic/rest-server))
- [AWS S3](https://restic.readthedocs.io/en/latest/manual.html#amazon-s3) (either from Amazon or using the [Minio](https://minio.io) server)
- [OpenStack Swift](https://restic.readthedocs.io/en/latest/manual.html#openstack-swift)
- [BackBlaze B2](https://restic.readthedocs.io/en/latest/manual.html#backblaze-b2)
- [Microsoft Azure Blob Storage](https://restic.readthedocs.io/en/latest/manual.html#microsoft-azure-blob-storage)
- [Google Cloud Storage](https://restic.readthedocs.io/en/latest/manual.html#google-cloud-storage)

Perhaps you could update the list? :)

Reference: https://github.com/restic/restic#backends

**Comment by Roman2K** [comment]
@rawtaz Thanks for the remark, you're absolutely right. I chose to stop comparing feature sets since it would easily get out of date and I surely don't want to have to maintain this section of the README.

And apologies for the huge delay in replying. I got lazy tackling open issues for lack of time and motivation to keep working on this project at the moment.

**Comment by rawtaz** [comment]
Understood, and no worries.

But perhaps it would be better to remove the comparison entirely then, as to not publish inaccurate information about "competing" projects. It does more harm than good I think.

**Comment by rawtaz** [comment]
Sorry, never mind the previous comment - I didn't notice that you had edited the README. Thanks!

**Comment by Roman2K** [comment]
@rawtaz 

> Sorry, never mind the previous comment - I didn't notice that you had edited the README. Thanks!

Ah, yes, sorry I didn't make this clear 🙈 I assumed the automatic GitHub issue closure message was more obvious than that.

**Comment by rawtaz** [comment]
Thing is, I get an e-mail with your comment, click the link to go to it on GitHub, and then it takes me to it but with the page scrolled so your comment's heading is at the top. I therefore don't see the closed sign. But I should pay more attention :)

**Comment by Roman2K** [comment]
Hehe, I see 😉 No problem.
